In [1]:
import numpy as np

In [3]:
data = np.random.randint(1,100,(10, 3))
print(data)

[[71 62 20]
 [ 8 57 74]
 [28 35 81]
 [31 54 99]
 [46 12 35]
 [15  4 85]
 [22 66 51]
 [ 7 99 49]
 [76 88 36]
 [98 39 88]]
